spring.application.name=DATN_NGUYENTHANHTUNG
server.port=8080

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB

spring.datasource.url=jdbc:postgresql://database.cvomge6kc9c1.ap-southeast-1.rds.amazonaws.com/clinic_management
spring.datasource.username=postgres
spring.datasource.password=ThanhTung2003
spring.datasource.driver-class-name=org.postgresql.Driver

aws.region=${AWS_REGION}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.s3-bucket-name=${AWS_S3_BUCKET_NAME}