"""
Django settings for projetc_datn project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from django.conf import settings
import os
from colorama import Fore, Style

# Hiển thị thông báo khởi động ứng dụng với màu sắc
print(Fore.RED + "CLINIC MANAGEMENT" + Fore.CYAN + " RUN " + Fore.MAGENTA + "APP" + Style.RESET_ALL)

# Đường dẫn gốc của dự án
BASE_DIR = Path(__file__).resolve().parent.parent

# Cấu hình thư mục media để lưu trữ file upload
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cấu hình thư mục img để lưu trữ hình ảnh
IMG_URL = '/img/'
IMG_ROOT = os.path.join(BASE_DIR, 'projetc_datn', 'img')

# Kiểm tra và hiển thị thông tin về thư mục img
print("IMG_ROOT:", settings.IMG_ROOT)
print("IMG_ROOT có tồn tại không:", os.path.exists(settings.IMG_ROOT))

full_path = os.path.join(settings.IMG_ROOT)
print("********* FULL PATH IMG:", full_path +" *********")
print("PATH IMG PUBLIC tồn tại:", os.path.exists(full_path))

# Cấu hình bảo mật
SECRET_KEY = '6qs0iilasstr+55s/avzaQ8/D/RBJcQKGxMFuBdfwX+Aw='
DEBUG = True
ALLOWED_HOSTS = ['do-an-tot-nghiep-ntu-api-gemini.onrender.com']

# Cấu hình các ứng dụng được cài đặt
INSTALLED_APPS = [
    # Các ứng dụng mặc định của Django
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Các thư viện bổ sung
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',

    # Các ứng dụng của dự án
    'apps.gemini_ai',       # Tích hợp AI
]

# Cấu hình middleware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Xử lý CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# # Cấu hình REST Framework
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }

# Cấu hình URL và template
ROOT_URLCONF = 'projetc_datn.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Cấu hình WSGI
WSGI_APPLICATION = 'projetc_datn.wsgi.application'

# Cấu hình cơ sở dữ liệu PostgreSQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'clinic_management',
        'USER': 'postgres',
        'PASSWORD': 'ThanhTung2003',
        'HOST': 'database.cvomge6kc9c1.ap-southeast-1.rds.amazonaws.com',
        'PORT': '5432',
    }
}

# Cấu hình xác thực mật khẩu
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Cấu hình ngôn ngữ và múi giờ
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Cấu hình file tĩnh
STATIC_URL = 'static/'

# Cấu hình trường khóa chính mặc định
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cấu hình CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
